#pragma config(Sensor, S1,     cs1,            sensorEV3_Color)
#pragma config(Sensor, S2,     cs2,            sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     cs3,            sensorEV3_Color)
#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define White 0
#define Yellow 1
#define Red 2
#define Blue 3

int gal = 10;

void setSpeed(int ls, int rs)
{
	setMotorSpeed(lm, ls);
	setMotorSpeed(rm, rs);
}
// sorting array arr by ascending
void bubbleSort(int* arr)
{
	int i, j, tmp;
	for (i = 0; i < 50 - 1; i++)
		for (j = 0; j < 50 - 1; j++)
			if (arr[j] > arr[j + 1])
			{
				tmp = arr[j + 1];
				arr[j] = arr[j + 1];
				arr[j + 1] = tmp;
			}
}

// get the color of the current location
int getColorTest()
{
	int red[50], green[50], blue[50];
	int r, g, b;

	setSpeed(0, 0);
	for (int i = 0; i < 50; i++)
	{
		getColorRGB(cs2, r, g, b);
		red[i] = r;
		green[i] = g;
		blue[i] = b;
		sleep(1);
	}
	setSpeed(30, 30);
	r = g = b = 0;
	bubbleSort(red); bubbleSort(green); bubbleSort(blue);
	for (int i = 10; i < 40; i++)
	{
		r += red[i];
		g += green[i];
		b += blue[i];
	}
	r /= 30;
	g /= 30;
	b /= 30;
	displayBigTextLine(1, "%d %d %d", r, g, b);
	return 0;
}

void getReflected()
{
	displayBigTextLine(1, "%d", getColorReflected(cs1));
	displayBigTextLine(4, "%d", getColorReflected(cs3));
}
task main()
{
	while(1){getReflected();}
}
